# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialsTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('imageUrl', models.CharField(default='', help_text='教师图片', max_length=300, verbose_name='教师图片')),
                ('desc', models.TextField(default='', help_text='教师描述', verbose_name='教师描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='TutorialsVedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='教程名')),
                ('htmlString', models.TextField(max_length=2000, verbose_name='视频地址的Html')),
                ('click_num', models.IntegerField(default=1000, verbose_name='点击数')),
                ('fav_num', models.IntegerField(default=10, verbose_name='收藏数')),
                ('video_front_image', models.CharField(default='', help_text='视频封面', max_length=300, verbose_name='视频封面')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorials.TutorialsTeacher', verbose_name='教程老师')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
